services:
  - type: web
    name: smartstudy-api-saikumarreddyappidi
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://saikumarreddyappidi.github.io
